version: 2
sources:
- name: "{{env_var('DATABASE_SCHEMA', var('source_schema', ''))}}"
  quoting:
    database: false
    schema: false
    identifier: false
  tables:
  - name: _airbyte_raw_get_merchant_listings_all_data

- name: "{{env_var('DATABASE_SCHEMA', var('source_schema', ''))}}"
  quoting:
    database: false
    schema: false
    identifier: false
  tables:
  - name: _airbyte_raw_get_fba_fulfillment_current_inventory_data
