version: 2
sources:
- name: "{{env_var('DATABASE_SCHEMA', var('source_schema', ''))}}"
  quoting:
    database: false
    schema: false
    identifier: false
  tables:
  - name: "{{env_var('SOURCE_RAW_MERCHANT_LISTING_ALL_DATA', var('source_table', ''))}}"

- name: "{{env_var('DATABASE_SCHEMA', var('source_schema', ''))}}"
  quoting:
    database: false
    schema: false
    identifier: false
  tables:
  - name: "{{env_var('SOURCE_RAW_FBA_FULFILLMENT_CURRENT_INVENTORY_REPORT', var('source_table', ''))}}"
